image: alpine:latest

stages:
  - build

build:
  stage: build
  image: python
  before_script:
    - pip3 install poetry
  script:
    - poetry version $CI_COMMIT_TAG
    - poetry install
    - poetry build
    - poetry publish -v --repository gitlab --username __token__ --password $CI_JOB_TOKEN
  only:
  - tags
  except:
  - branches
