image: alpine:latest

stages:
  - build
  - push

build:
  stage: build
  image: python
  before_script:
    - pip3 install poetry
  script:
    - poetry version $CI_COMMIT_TAG
    - poetry install
    - poetry build
    - poetry publish --repository gitlab --username gitlab-ci-token --password $CI_JOB_TOKEN
  only:
  - tags
  except:
  - branches
  artifacts:
    expire_in: 15m
    paths:
      - dist/cloud_utils-$CI_COMMIT_TAG.tar.gz
      - dist/cloud_utils-$CI_COMMIT_TAG-py3-none-any.whl

push:
  stage: push
  needs:
    - build
  image:
    name: "amazon/aws-cli:latest"
    entrypoint:
      - "/bin/sh"
      - "-c"
  script:
    - s3 cp --recursive .dist/ s3://hs-core-packages/cloud_utils/$CI_COMMIT_TAG/
